application: silex-skeleton
version: 1
runtime: php
api_version: 1

handlers:
- url: /css
  static_dir: web/css

- url: /fonts
  static_dir: web/fonts

- url: /js
  static_dir: web/js

- url: /.*
  script: web/app.php