version: '3'

services:
    app:
        restart: unless-stopped
        build: .
        image: symlex/symlex:develop
        command: rr serve -d --override http.workers.pool.maxJobs=1 # no caching - only for development!
        ports:
            - "8081:8081" # Roadrunner PHP application server
        depends_on:
            - db
            - redis
            - mailhog
        volumes:
            - ./:/var/www/html
            - node-data:/var/www/html/frontend/node_modules
            - /dev/shm:/dev/shm
        environment: # Can be set dynamically when deploying with Kubernetes
            - APP_URL=http://localhost:8081/
            - APP_EMAIL=info@example.com
            - MAILER_HOST=mailhog
            - MAILER_PORT=1025
            - MAILER_ENCRYPTION=tcp
            - MAILER_USERNAME=
            - MAILER_PASSWORD=
            - MAILER_AUTH_MODE=
            - MYSQL_HOST=db
            - MYSQL_NAME=web
            - MYSQL_USER=web
            - MYSQL_PASSWORD=web
            - REDIS_HOST=redis
            - VIRTUAL_HOST=symlex.local
            - VIRTUAL_PORT=8081

    db:
        restart: unless-stopped
        image: mariadb:10
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512
        ports:
            - "3306:3306"
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: web
            MYSQL_PASSWORD: web
            MYSQL_DATABASE: web

    redis:
        restart: unless-stopped
        image: redis:3-alpine

    mailhog:
        restart: unless-stopped
        image: mailhog/mailhog
        ports:
            - "8082:8025"
        environment:
            - VIRTUAL_HOST=mailhog.local
            - VIRTUAL_PORT=8025

volumes:
    node-data:
        driver: local
    db-data:
        driver: local

networks:
    default:
        driver: bridge