version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        depends_on:
            - php
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - symlex-network
    php:
        build: ./docker/php
        depends_on:
            - mysql
        volumes:
            - ./:/var/www/html
        networks:
            - symlex-network
    mysql:
        image: mysql
        ports:
            - "3306:3306"
        volumes:
            - ./:/var/www/html
        environment:
            MYSQL_ROOT_PASSWORD: silex
            MYSQL_USER: silex
            MYSQL_PASSWORD: silex
            MYSQL_DATABASE: silex
        networks:
            - symlex-network

networks:
    symlex-network:
        driver: bridge