services:
    controller.web.index:
        class: App\Controller\Web\IndexController

    controller.web.auth:
        class: App\Controller\Web\AuthController
        arguments: [ "@service.session", "@model.user", "@service.mail" ]

    controller.rest.users:
        class: App\Controller\Rest\UsersController
        arguments: [ "@service.session", "@model.user", "@form.factory", "@service.mail" ]