parameters:
    app.name: 'App'
    app.version: '1.0'
    app.url: 'http://localhost:8080/'
    app.email: 'root@localhost'
    app.locale: en
    db.host: db
    db.port: 3306
    db.name: web
    db.user: web
    db.password: web
    mailer.host: mailhog
    mailer.port: 1025
    mailer.encryption: null
    mailer.username: ''
    mailer.password: ''
    mailer.auth_mode: ''
    minified_js: true
    minified_css: true