parameters:
    app.name: Symlex
    app.version: '1.0'
    app.url: 'http://localhost:8080/'
    app.email: 'root@localhost'

    db.options:
        driver: pdo_mysql
        host: mysql
        dbname: silex
        user: silex
        password: silex
        port: ~
        unix_socket: ~

    mailer.host: smtp.gmail.com
    mailer.port: 587
    mailer.encryption: tls
    mailer.username: ''
    mailer.password: ''
    mailer.auth_mode: ''