parameters:
    app.name: 'Silex Boilerplate'
    app.version: '1.0'

    db.options:
        driver: mysqli
        host: '127.0.0.1'
        dbname: 'silex'
        user: 'silex'
        password: 'silex'
        port: ~
        unix_socket: ~