imports:
    - { resource: mailer.yml }

services:
    log.handler:
        class: Monolog\Handler\StreamHandler
        arguments: [ '%app.log_path%/%app.environment%.log' ]

    log:
        class: Monolog\Logger
        arguments: [ 'main' ]
        calls:
            - [ pushHandler, [@log.handler] ]

    db.driver:
        class: Doctrine\DBAL\Driver\Mysqli\Driver

    db:
        class: Doctrine\DBAL\Connection
        arguments:
            - %db.options%
            - @db.driver

    message_selector:
        class: Symfony\Component\Translation\MessageSelector

    yaml_loader:
        class: Symfony\Component\Translation\Loader\YamlFileLoader

    array_loader:
        class: Symfony\Component\Translation\Loader\ArrayLoader

    translator:
        class: Symfony\Component\Translation\Translator
        arguments: ['de', @message_selector]
        calls:
          - [ addLoader, ['yaml', @yaml_loader] ]
          - [ addLoader, ['array', @array_loader]]
          - [ addResource, ['yaml', '%app.path%/l10n/de.yml', 'de'] ]
          - [ addResource, ['yaml', '%app.path%/l10n/en.yml', 'en'] ]

    validator:
        class: Sympathy\Form\Validator

    form:
        class: App\Form\Form
        arguments: [ @translator, @validator ]

    form.user:
        class: App\Form\UserForm
        arguments: [ @translator, @validator ]

    model.user:
        class: App\Model\User
        scope: prototype
        arguments: [ @db ]

    service.mail:
        class: App\Service\Mail
        scope: prototype
        arguments: [ @mailer, @twig, { %app.email%: %app.name%} ]