imports:
    - { resource: parameters.yml }
    - { resource: services.yml }
    - { resource: twig.yml }
    
parameters:
    exception.codes:
        InvalidArgumentException: 400
        Exception\NotFoundException: 404
        Sympathy\Silex\Router\NotFoundException: 404
        Exception: 500

    exception.messages:
        400: 'Bad request'
        401: 'Unauthorized'
        402: 'Payment Required'
        403: 'Forbidden'
        404: 'Not Found'
        405: 'Method Not Allowed'
        406: 'Not Acceptable'
        407: 'Proxy Authentication Required'
        408: 'Request Timeout'
        409: 'Conflict'
        410: 'Gone'
        500: 'Looks like something went wrong!'

services:
    app:
        class: Silex\Application

    controller.web.index:
        class: App\Controller\IndexController
        arguments: [ @app, @twig ]

    controller.rest.user:
        class: App\Rest\UserController
        arguments: [ @app, @twig ]

    router.rest:
        class: Sympathy\Silex\Router\RestRouter
        arguments: [ @app, @service_container ]

    router.twig:
        class: Sympathy\Silex\Router\TwigRouter
        arguments: [ @app, @service_container, @twig ]

    router.error:
        class: Sympathy\Silex\Router\ErrorRouter
        arguments: [ @app, @twig, %exception.codes%, %exception.messages%, %app.debug% ]