imports:
    - { resource: parameters.yml }
    - { resource: services.yml }
    - { resource: exceptions.yml }
    - { resource: controllers.yml }

services:
    app:
        class: Silex\Application

    request:
        class: Symfony\Component\HttpFoundation\Request

    session:
        class: Symfony\Component\HttpFoundation\Session\Session

    service.session:
        class: App\Service\Session
        arguments: [ "@session", "@model.user" ]

    router.rest:
        class: App\Router\RestRouter
        arguments: [ "@app", "@service_container" ]
        calls:
            - [ setSession, [ "@service.session" ] ]

    router.twig:
        class: App\Router\TwigRouter
        arguments: [ "@app", "@service_container", "@twig" ]
        calls:
            - [ setSession, [ "@service.session" ] ]

    router.error:
        class: Symlex\Router\ErrorRouter
        arguments: [ "@app", "@twig", %exception.codes%, %exception.messages%, %app.debug% ]