imports:
    - { resource: parameters.yml }
    - { resource: common.yml }
    - { resource: exceptions.yml }
    - { resource: rest.yml }

services:
    app:
        class: Silex\Application

    request:
        class: Symfony\Component\HttpFoundation\Request
        factory: [ 'Symfony\Component\HttpFoundation\Request', createFromGlobals ]

    service.session:
        class: App\Service\Session
        arguments: [ "@cache", "@request", "@model.user" ]

    router.error:
        class: App\Router\ErrorRouter
        arguments: [ "@app", "@twig", %exception.codes%, %exception.messages%, %app.debug% ]
        calls:
            - [ setLogger, [ "@log" ] ]

    router.twig:
        class: Symlex\Router\TwigRouter
        arguments: [ "@app", "@service_container", "@twig" ]

    router.twig_default:
        class: Symlex\Router\TwigDefaultRouter
        arguments: [ "@app", "@service_container", "@twig" ]

    controller.web.index:
        class: App\Controller\Web\IndexController